# File: .github/workflows/ci.yml
name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Maven Validate
        run: mvn validate --batch-mode

      - name: Maven Compile
        run: mvn compile --batch-mode

      - name: Maven Test
        run: mvn test --batch-mode

      - name: Maven Package
        run: mvn package --batch-mode

      - name: Maven Verify
        run: mvn verify --batch-mode